version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      # DB_PASS: "${DB_PASS}"
      # DB_USER: "${DB_USER}"
      # DB_API: "${DB_API}"
      # DB_CORE: "${DB_CORE}"
    expose:
      - "5433:5433"
    volumes:
      - ./data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
