version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn fpdata.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    links:
      - db:db
    networks:
      - postgres
      - djangonetwork
  db:
    container_name: pg_container
    image: postgres
    restart: unless-stopped
    env_file:
      - ./.env.prod.db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    networks:
      - postgres
      - djangonetwork
    volumes:
      - postgres:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - ./.env.pgadmin
    volumes:
      - pgadmin:/var/lib/pgadmin/data
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
  djangonetwork:
    driver: bridge

volumes:
  postgres:
  pgadmin:
