version: '3'

services:

  postgres:
    build:
      context: ./postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: postgres
    restart: always
    ports:
      - "5433:5433"
    expose:
      - "5433:5433"
    env_file:
      - .env
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
