version: '3'

services:

  postgres:
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_PASS: "${DB_PASS}"
      DB_USER: "${DB_USER}"
      DB_API: "${DB_API}"
      DB_CORE: "${DB_CORE}"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql/stars.sql:/docker-entrypoint-initdb.d/stars.sql
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
