version: '3'

services:

  postgres:
    build:
      context: ./postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: postgres
    restart: always
    ports:
      - "5433:5433"
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
