# Generated by Django 3.2.16 on 2022-12-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ztffpsdata',
            options={'ordering': ['index']},
        ),
    ]
