# Generated by Django 3.2.16 on 2022-12-05 21:57

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('fpdata', '0002_alter_ztffpsdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ztffpsdata',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('jd'), descending=True, nulls_last=True)]},
        ),
    ]
