# Generated by Django 3.2.16 on 2022-11-19 20:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PandasData',
            fields=[
                ('index', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.IntegerField()),
                ('ccdid', models.IntegerField()),
                ('qid', models.IntegerField()),
                ('filter', models.CharField(blank=True, max_length=5, null=True)),
                ('pid', models.IntegerField()),
                ('infobitssci', models.IntegerField()),
                ('sciinpseeing', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('scibckgnd', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('scisigpix', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('zpmaginpsci', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('zpmaginpsciunc', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('zpmaginpscirms', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('clrcoeff', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('clrcoeffunc', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('ncalmatches', models.IntegerField()),
                ('exptime', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('adpctdif1', models.IntegerField()),
                ('adpctdif2', models.IntegerField()),
                ('diffmaglim', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('zpdiff', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('programid', models.IntegerField()),
                ('jd', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('rfid', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('forcediffimflux', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('forcediffimfluxunc', models.CharField(blank=True, max_length=1, null=True)),
                ('forcediffimsnr', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('forcediffimchisq', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('forcediffimfluxuncap', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('forcediffimsnrap', models.IntegerField()),
                ('aperturecorr', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('dnearestrefsrc', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('nearestrefmag', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('nearestrefmagunc', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('nearestrefchi', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('nearestrefsharp', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('refjdstart', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('refjdend', models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True)),
                ('procstatus', models.IntegerField()),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
