# Generated by Django 3.2.16 on 2022-11-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztfdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandasdata',
            name='pid',
            field=models.BigIntegerField(),
        ),
    ]
