# Generated by Django 3.2.16 on 2022-12-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztfdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pandasdata',
            options={},
        ),
    ]
