# Generated by Django 3.2.16 on 2022-11-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztfdata', '0002_alter_pandasdata_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandasdata',
            name='adpctdif1',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='adpctdif2',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='aperturecorr',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='clrcoeff',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='clrcoeffunc',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='diffmaglim',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='dnearestrefsrc',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='exptime',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='filter',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='forcediffimchisq',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='forcediffimflux',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='forcediffimfluxap',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='forcediffimfluxunc',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='forcediffimfluxuncap',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='forcediffimsnr',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='forcediffimsnrap',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='jd',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='nearestrefchi',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='nearestrefmag',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='nearestrefmagunc',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='nearestrefsharp',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='procstatus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='refjdend',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='refjdstart',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='rfid',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='scibckgnd',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='sciinpseeing',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='scisigpix',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='zpdiff',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='zpmaginpsci',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='zpmaginpscirms',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='zpmaginpsciunc',
            field=models.DecimalField(decimal_places=15, max_digits=100, null=True),
        ),
    ]
