# Generated by Django 3.2.16 on 2022-11-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztfdata', '0002_alter_pandasdata_adpctdif1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandasdata',
            name='adpctdif2',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True),
        ),
    ]
