# Generated by Django 3.2.16 on 2022-11-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztfdata', '0003_auto_20221130_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pandasdata',
            options={'ordering': ['field']},
        ),
        migrations.RemoveField(
            model_name='pandasdata',
            name='index',
        ),
        migrations.AlterField(
            model_name='pandasdata',
            name='field',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
