# Generated by Django 3.2.16 on 2022-11-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztfdata', '0004_alter_pandasdata_forcediffimfluxunc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandasdata',
            name='forcediffimfluxap',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True),
        ),
    ]
