# Generated by Django 3.2.16 on 2022-11-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztfdata', '0005_pandasdata_forcediffimfluxap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandasdata',
            name='forcediffimsnrap',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True),
        ),
    ]
