# Generated by Django 3.2.16 on 2022-11-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztfdata', '0006_alter_pandasdata_forcediffimsnrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandasdata',
            name='index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
